# Generated by Django 3.2.7 on 2023-05-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photo', verbose_name='Фото')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Наполнение сайта',
                'verbose_name_plural': 'Наполнение сайта',
            },
        ),
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots', models.TextField(blank=True, null=True, verbose_name='robots.txt')),
                ('script', models.TextField(blank=True, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цвет')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.blog', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Описание заказа',
                'verbose_name_plural': 'Описание заказа',
            },
        ),
    ]
