# Generated by Django 3.2.7 on 2023-05-26 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 26, 13, 16, 51, 618540)),
            preserve_default=False,
        ),
    ]
